#ifndef MODEL_META_H
#define MODEL_META_H

#include "types.h"
#include "runtime_config.h"

/* Layer metadata */
typedef struct {
    layer_type_t type;
    tensor_shape_t input_shape;
    tensor_shape_t output_shape;
    uint32_t weight_offset;    /* Offset into model.h weight arrays */
    uint32_t bias_offset;
} layer_meta_t;

/* Full model metadata */
typedef struct {
    layer_meta_t layers[MAX_LAYERS];
    uint32_t     num_layers;
    tensor_shape_t model_input_shape;
    tensor_shape_t model_output_shape;
} model_meta_t;

/* Generated by onnx_to_c.py — declared here, defined in model.h */
extern const model_meta_t g_model_meta;

#endif /* MODEL_META_H */
